server:
  port: 9320

spring:
  application:
    name: ruoyi-permission-center
  profiles:
    active: ${spring.profiles.active:dev}

---
spring:
  cloud:
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr:127.0.0.1:8848}
      username: ${spring.cloud.nacos.username:nacos}
      password: ${spring.cloud.nacos.password:nacos}
      discovery:
        group: ${spring.cloud.nacos.discovery.group:DEFAULT_GROUP}
        namespace: ${spring.profiles.active}
      config:
        group: ${spring.cloud.nacos.config.group:DEFAULT_GROUP}
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml
