apiVersion: v1
kind: Service
metadata:
  name: ruoyi-auth
  namespace: ruoyi
  labels:
    app.kubernetes.io/name: auth
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth
  ports:
    - name: http
      port: 9210
      targetPort: 9210
      protocol: TCP
