apiVersion: v1
kind: Service
metadata:
  name: ruoyi-permission-center
  namespace: ruoyi
  labels:
    app.kubernetes.io/name: permission-center
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: permission-center
  ports:
    - name: http
      port: 9320
      targetPort: 9320
      protocol: TCP
